#include "nsISupports.idl"

interface nsIURI;

[scriptable, uuid(e145a100-e070-11df-85ca-0800200c9a66)]
interface IZimCluceneIndexer : nsISupports
{
  boolean start(in AString zimFilePath, in AString cluceneDirectoryPath);
  boolean stop();
  boolean getProgression(out PRUint32 progression);
  boolean isRunning();
};
