#include "nsISupports.idl"

interface nsIURI;

[scriptable, uuid(9EF75262-FA0D-11DD-A24C-006455D89593)]
interface IXapianAccessor : nsISupports
{
  boolean openReadableDatabase(in AUTF8String unixXapianDirectoryPath, in ACString winXapianDirectoryPath);
  boolean search(in AUTF8String search, in PRUint32 resultStart, in PRUint32 resultEnd);
  boolean reset();
  boolean getNextResult(out AUTF8String url, out AUTF8String title, out PRUint32 score);
  boolean setResultTemplatePath(in AUTF8String unixResultTemplatePath, in ACString winResultTemplatePath);
  boolean getHtml(out ACString html);
  boolean closeReadableDatabase();
};
