#include "nsISupports.idl"

interface nsIURI;

[scriptable, uuid(3eef338e-b7a5-4d7e-8bac-4c0bca542a85)]
interface IZimIndexer : nsISupports
{
  boolean startIndexing(in AUTF8String zimPath, in AUTF8String indexPath, in AUTF8String backend);
  boolean getStatus(out PRUint32 percentage);
  boolean stopIndexing();
};
