#include "nsISupports.idl"

interface nsIURI;
interface nsACString;

[scriptable, uuid(0e41f9d0-f08e-11dd-ba2f-0800200c9a66)]
interface IZimAccessor : nsISupports
{
  boolean loadFile(in string path);
  boolean getNextArticle(out string url, out string content);
  boolean reset();
  ACString getContent(in nsIURI url, out string contentType);
};
