#include "nsISupports.idl"

interface nsIURI;

[scriptable, uuid(9be3f6b2-31a3-4aed-8e58-2b6ca04babf0)]
interface IZimXapianIndexer : nsISupports
{
  boolean start(in AString zimFilePath, in AString xapianDirectoryPath);
  boolean stop();
  boolean isRunning();
};
