#include "nsISupports.idl"

interface nsIURI;

[scriptable, uuid(0e41f9d0-f08e-11dd-ba2f-0800200c9a66)]
interface IZimAccessor : nsISupports
{
  boolean loadFile(in AUTF8String path);
  boolean getMainPageUrl(out AUTF8String url);
  boolean getRandomPageUrl(out AUTF8String url);
  boolean getId(out ACString id);
  boolean getArticleCount(out PRUint32 count);
  boolean reset();
  boolean getMetatag(in ACString name, out ACString value);
  boolean getContent(in nsIURI url, out ACString content, out PRUint32 contentLength, out ACString contentType);
  boolean searchSuggestions(in AUTF8String prefix, in PRUint32 resultsCount);
  boolean getNextSuggestion(out AUTF8String title);
};
