Document: kiwix
Title: Debian kiwix Manual
Author: <insert document author here>
Abstract: This manual describes what kiwix is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kiwix/kiwix.sgml.gz

Format: postscript
Files: /usr/share/doc/kiwix/kiwix.ps.gz

Format: text
Files: /usr/share/doc/kiwix/kiwix.text.gz

Format: HTML
Index: /usr/share/doc/kiwix/html/index.html
Files: /usr/share/doc/kiwix/html/*.html
