<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
} elseif ( empty( $wgNoOutputBuffer ) ) {
	## Compress output if the browser supports it
	if( !ini_get( 'zlib.output_compression' ) ) @ob_start( 'ob_gzhandler' );
}

$wgLogo = "/leroilion_pumbaa.gif";
// include lang references.
include("../".$moulinLANG."/config.php");


## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL

$wgEnableEmail      = false;
$wgEnableUserEmail  = false;

$wgEmergencyContact = "admin@localhost";
$wgPasswordSender = "admin@localhost";

## For a detailed description of the following switches see
## http://meta.wikimedia.org/Enotif and http://meta.wikimedia.org/Eauthent
## There are many more options for fine tuning available see
## /includes/DefaultSettings.php
## UPO means: this is also a user preference option
$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = false;

$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBport           = "5432";
$wgDBprefix         = "";

# Schemas for Postgres
$wgDBmwschema       = "mediawiki";
$wgDBts2schema      = "public";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
//$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = false;
$wgUseImageResize      = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = true;

$wgLocalInterwiki   = $wgSitename;

$wgProxyKey = "e849d3c4925b25e9e55b45d1b91d10467ed5e8519f720a6f403024b14e892cee";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'htmldump';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$configdate = gmdate( 'YmdHis', @filemtime( __FILE__ ) );
$wgCacheEpoch = max( $wgCacheEpoch, $configdate );

## extensions inclusion
#include("extensions/CategoryTree/CategoryTree.php");
#include("extensions/CategoryTree/CategoryTreeFunctions.php");
include("extensions/Cite/Cite.php");
include("extensions/Cite/SpecialCite.php");
include("extensions/CrossNamespaceLinks/SpecialCrossNamespaceLinks.php");
include("extensions/Filepath/SpecialFilepath.php");
include("extensions/LuceneSearch/LuceneSearch.php");
include("extensions/Makebot/Makebot.php");
include("extensions/Makesysop/SpecialMakesysop.php");
include("extensions/OAI/OAIRepo.php");
include("extensions/Renameuser/SpecialRenameuser.php");
include("extensions/SiteMatrix/SiteMatrix.php");
include("extensions/CharInsert/CharInsert.php");
include("extensions/ImageMap/ImageMap.php");
include("extensions/inputbox/inputbox.php");
include("extensions/ParserFunctions/ParserFunctions.php");
include("extensions/Poem/Poem.php");
include("extensions/wikihiero/wikihiero.php");
include("extensions/ConfirmEdit/ConfirmEdit.php");
include("extensions/ConfirmEdit/FancyCaptcha.php");
include("extensions/ConfirmEdit/MathCaptcha.php");
include("extensions/Newuserlog/Newuserlog.php");
include("extensions/SpamBlacklist/SpamBlacklist.php");
include("extensions/UsernameBlacklist/UsernameBlacklist.php");
include("extensions/timeline/Timeline.php");

include("extensions/FixedImage/FixedImage.php");
include("extensions/CheckUser/CheckUser.php");
include("extensions/Oversight/HideRevision.php");
include("extensions/LinkSearch/LinkSearch.php");
include("extensions/AntiSpoof/AntiSpoof.php");
include("extensions/BoardVote/BoardVote.php");
include("extensions/DismissableSiteNotice/DismissableSiteNotice.php");
