TEMPLATE = app
QT = gui core
CONFIG += qt release warn_on console
DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
FORMS = ui/app.ui
HEADERS = src/appimpl.h
SOURCES = src/appimpl.cpp src/main.cpp
RESOURCES += src/autorun.qrc
