#include "nsISupports.idl"

interface nsIURI;
interface nsILocalFile;

[scriptable, uuid(041c2a90-74f1-11e0-a1f0-0800200c9a66)]
interface IContentManager : nsISupports
{
  boolean openLibraryFromFile(in nsILocalFile path);
  boolean writeLibraryToFile(in nsILocalFile path);
  boolean writeLibrary();
  boolean removeBookById(in ACString id);
  boolean addBookFromPath(in nsILocalFile path);
  boolean getBookById(in ACString id, out ACString path, out ACString title, 
		      out ACString indexPath, out ACString indexType);
  boolean setCurrentBookId(in ACString id);
  boolean getCurrentBookId(out ACString id);
};
